id: IDCED36B7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:08:53+00:00'
last_modified: '2022-06-07T14:13:52.029275+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21718
  title: སྒྲ་བསྒྱུར་མར་པ་ལོ་ཙཱའི་རྣམ་པར་ཐར་པ་མཐོང་བ་དོན་ཡོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    09E9:
      image_group_id: I1GS56153
      title: ''
      total_pages: 137
      order: 1
      base_file: 09E9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
